---
title: "Modelling management legacies & climate change impacts on tree mortality"
output: github_document
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
pre {
  font-size: 10px
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = T, warning = F,
                      message = F)
```

```{r libraries}
library(tidyverse)
library(here)
library(patchwork)
library(sf)
library(viridis)
library(glmmTMB)
library(DHARMa)
library(corrr)
library(bbmle)
library(MASS, exclude = "select")
library(performance)
library(ggdist)
library(RColorBrewer)
library(testthat)
```

```{r read-data}
dem_clim <- read_csv(
  here("01-data", "legacies", "dem_clim_ps_cut.csv")
)

table(dem_clim$k3)
table(dem_clim$type2.x)
summary(dem_clim$Mortality23)

dem_clim <- dem_clim |> 
  unite("k_type", k3:type2.x) |> 
  mutate(
    mort_real = if_else(
      Cut32 == 0, Mortality_ausente23 + Mortality23, 
      Mortality23
    )
  )
 
table(dem_clim$k_type)
```

# Exploratory data analyses

```{r EDA}
glimpse(dem_clim)

summary(dem_clim$mort_real)
summary(dem_clim$WAIplot)
summary(dem_clim$speimin)

ggplot(dem_clim) +
  geom_histogram(aes(mort_real), bins = 50)

map_loc <- map_data("world", region = c("Portugal", "Spain", "France",
                                        "Andorra")) |> 
  ggplot(aes(x = long, y = lat)) + 
  geom_polygon(aes(group = group), 
               fill = "white", 
               color = "grey") +
  coord_fixed(xlim = c(-11, 5),  
              ylim = c(35, 45), 
              ratio = 1.3) +
  xlab("Longitude") +
  ylab("Latitude") + 
  theme(legend.title = element_text(colour = "black", face = "bold", size = 12),
        legend.position = c(0.9, 0.2),
        legend.text = element_text(size = 11),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),  
        axis.text.x = element_text(colour = "grey50", size = 8),
        axis.text.y = element_text(colour = "grey50", size = 8),
        axis.ticks = element_blank(),
        panel.grid.major = element_line(colour = "grey90", size = 0.5), 
        axis.line = element_blank(),
        panel.background = element_blank()) 

# set as sf and assign crs
dem_clim_sf <- st_as_sf(x = dem_clim, 
                        coords = c("CX", "CY"),
                        crs = "+proj=utm +zone=30 +ellps=intl +units=m +no_defs")
st_crs(dem_clim_sf)

ggplot() + 
  geom_sf(data = dem_clim_sf)

# transform to long lat
dem_clim_sf_map <- st_transform(
  dem_clim_sf,
  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
)

st_crs(dem_clim_sf_map)

# convert to tibble
dem_clim_sp_tb <- dem_clim_sf_map |>
  ungroup() |> 
  mutate(CX = unlist(map(dem_clim_sf_map$geometry, 1)),
         CY = unlist(map(dem_clim_sf_map$geometry, 2))) |> 
  as_tibble() |> 
  dplyr::select(!geometry)

map_plot <- function(col){
  map_loc + 
    geom_point(data = dem_clim_sp_tb,
               aes(CX, CY, color = .data[[col]]), size = .5, alpha = .8) + 
    scale_color_viridis() +
    xlab("") +
    ylab("") + 
    theme(plot.margin = margin(0, 0, 0, 0),
          legend.title = element_text(color = "black", size = 9),
          legend.text = element_text(size = 9),
          legend.key = element_blank(),
          legend.position = "top",
          legend.justification = "left",
          legend.background = element_rect(fill = "white", colour = NA),
          axis.title = element_blank(),
          axis.text.x = element_text(colour = "grey50", size = 7),
          axis.text.y = element_text(colour = "grey50", size = 7),
          panel.grid.major = element_line(colour = "grey90", size = 0.5), 
          axis.line = element_blank(),
          panel.background = element_blank())
}

map_plot("WAIplot") + map_plot("speimin")

# full data
gg_mort <- function(x){
  dem_clim |> 
    ggplot(aes(x = .data[[x]], y = Mortality23)) + 
    geom_hex() + 
    ggtitle("Full data = ")
}

var_int_all <- c(
  "WAIplot", "speimin", "k_type"
)

map(var_int_all, ~gg_mort(.)) |> 
  reduce(`/`)

ggsave(
  here("03-results", "others", "distri_explanatory.png"),
  width = 12, height = 4
)

# n. of plots
nrow(dem_clim)

# n. of plots with any dead trees
sum(dem_clim$Mortality23 > 0)

## correlations ------------------------------------------------------------
corm <- dem_clim |>
  dplyr::select(
    WAIplot, speimin
  ) |>
  corrr::correlate(diagonal = 1) |>
  corrr::shave(upper = FALSE) |>
  pivot_longer(
    cols = -term,
    names_to = "colname",
    values_to = "corr"
  ) |>
  mutate(term = fct_inorder(term),
         colname = fct_inorder(colname))

gg_cor <- ggplot(corm, aes(term, fct_rev(colname),
                 fill = corr)) +
  geom_tile() +
  geom_text(aes(
    label = format(round(corr, 2), nsmall = 2),
    color = abs(corr) < .60)) +
  coord_fixed(expand = FALSE) +
  scale_color_manual(values = c("white", "black"),
                     guide = "none") +
  scale_fill_distiller(
    palette = "PuOr", na.value = "white",
    direction = 1, limits = c(-1, 1)) +
  labs(x = NULL, y = NULL) +
  theme(panel.border = element_rect(color = NA, fill = NA),
        legend.position = c(.85, .8))

gg_cor
  
ggsave(
  plot = gg_cor,
  here("03-results", "si_figures", "s4_correlations.png"),
  width = 3.5, height = 5,
  dpi = 600
)
```

# Modelling

```{r modelling}
# https://stackoverflow.com/questions/65745148/is-there-a-difference-between-gamma-hurdle-two-part-models-and-zero-inflated-g

zigamma_model_1 <- glmmTMB(
  mort_real ~ k_type * WAIplot * speimin,
  family = ziGamma(link = "log"),
  # we assume that absences will at least vary by:
  ziformula = ~ k_type * WAIplot * speimin,
  data = dem_clim
  )

# model output interpretation:
# https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf
# https://cran.r-project.org/web/packages/glmmTMB/glmmTMB.pdf
# https://cran.r-project.org/web/packages/glmmTMB/vignettes/glmmTMB.pdf
summary(zigamma_model_1)
# This summary can be broken down into 3 sections.

# The top section is a general overview
# containing a description of the model specification
# (Family, Formula, Zero inflation, Dispersion
# Data) and resulting information criteria

# The second section describes the coefficients 
# of the Conditional model
# including Wald Z statistics and p-values. 
# Apart from the intercept, the estimates are all
# contrasts as is standard in regression models.
# This model has a log link as stated in the 
# top line of the summary

# The third section describes the Zero-inflation model 
# similarly to the Conditional model except that
# this model has a logit link. The zero-inflation model 
# estimates the probability of an extra zero such that
# a positive contrast indicates a higher chance of
# absence; this is the opposite of
# the conditional model where a positive contrast 
# indicates a higher abundance

zigamma_model_2 <- glmmTMB(
  mort_real ~ k_type * WAIplot + k_type * speimin,
  family = ziGamma(link = "log"),
  # we assume that absences will at least vary by:
  ziformula = ~ k_type * WAIplot * speimin,
  data = dem_clim
)

summary(zigamma_model_2)

zigamma_model_3 <- glmmTMB(
  mort_real ~ WAIplot + k_type * speimin,
  family = ziGamma(link = "log"),
  # we assume that absences will at least vary by:
  ziformula = ~ k_type * WAIplot * speimin,
  data = dem_clim
)

summary(zigamma_model_3)

zigamma_model_4 <- glmmTMB(
  mort_real ~ speimin + k_type * WAIplot,
  family = ziGamma(link = "log"),
  # we assume that absences will at least vary by:
  ziformula = ~ k_type * WAIplot * speimin,
  data = dem_clim
)

summary(zigamma_model_4)

bbmle::AICtab(
  zigamma_model_1,
  zigamma_model_2,
  zigamma_model_3,
  zigamma_model_4
  )

# https://cran.r-project.org/web/packages/glmmTMB/vignettes/model_evaluation.pdf

## model checking and diagnostics ------------------------------------------
# https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html
zigamma_model_simres_1 <- simulateResiduals(zigamma_model_1)
x11()
# par(mfrow = c(2, 2))
plot(zigamma_model_simres_1)

# plotResiduals(zigamma_model_simres_1)
# plotQQunif(zigamma_model_simres_1)
# testZeroInflation(zigamma_model_simres_1)

x11()
testDispersion(zigamma_model_simres_1)
# shows your actual dispersion
# with a histogram of simulated residuals. 
# Since your value is to the right it indicates
# that your model has over-dispersion
plot(check_predictions(zigamma_model_1)) +
  coord_cartesian(xlim = c(0, 0.02))

testZeroInflation(zigamma_model_simres_1)
# shows the simulated number
# of zeroes with your actual number shown as red. 
# we have the same number as expected
# so there is no zero-inflation now
# makes sense to fit a zero-inflated model

# sensitivity analysis
# predict_real <- predict(
#   object = zigamma_model_1, newdata = dem_clim,
#   se.fit = TRUE, type = "conditional"
# )
# 
# dem_clim_pred <- dem_clim |>
#   mutate(
#     predFE = predict_real$fit
#   )
# 
# dem_clim_pred_n0 <- dem_clim_pred |>
#   filter(mort_real > 0)
# 
# ggplot(dem_clim_pred_n0, aes(
#   mort_real, predFE
#   )) +
#   geom_point(alpha = .7) +
#   geom_abline(intercept = 0, slope = 1, color = "red") +
#   coord_cartesian(xlim = c(0, .08), ylim = c(0, .08))

## predictions -------------------------------------------
summary(zigamma_model_1)

# zigamma_model_1 <- zigamma_model_1 

# newdata
# change climate
# reduction in WAI & spei per plot equal to 
# the difference between the median & the 1st Qu
summary(dem_clim$WAIplot)
summary(dem_clim$speimin)

dem_clim_cc <- dem_clim |> 
  mutate(
    WAIplot = WAIplot - 18.435,
    speimin = speimin - 0.069
  )

# change legacy for planted plots + climate impact
dem_clim_c2p_cc <- dem_clim |> 
    filter(
    k_type == "1_Planted" |
      k_type == "2_Planted"
    ) |> 
  mutate(
    k_type = "2_Planted",
    WAIplot = WAIplot - 18.435,
    speimin = speimin - 0.069
  )

dem_clim_c2n_cc <- dem_clim |> 
    filter(
    k_type == "1_Natural" |
      k_type == "2_Natural"
    ) |> 
  mutate(
    k_type = "2_Natural",
    WAIplot = WAIplot - 18.435,
    speimin = speimin - 0.069
  )

dem_clim_new <- list(
  dem_clim_cc,
  dem_clim_c2p_cc,
  dem_clim_c2n_cc
)

# https://www.rdocumentation.org/packages/glmmTMB/versions/1.1.3/topics/predict.glmmTMB
dem_clim_pred <- map(dem_clim_new, ~predict(
  object = zigamma_model_1, newdata = .x,
  se.fit = TRUE, type = "conditional"
))

# add predictions to the corresponding dataset
add_predictions <- function(dat, pred){
  dat |> 
    mutate(
      predFE = pred$fit
    )
}

arg2_dat_pred <- list(
  dat = dem_clim_new, 
  pred = dem_clim_pred
  )

dem_clim_new_pred <- arg2_dat_pred |>
  pmap(add_predictions)

# add observed data
## all plots
dem_clim_obs_all <- dem_clim

## only planted plots
dem_clim_obs_p <- dem_clim |> 
  filter(
    k_type == "1_Planted" |
      k_type == "2_Planted"
    ) 

## only natural plots
dem_clim_obs_n <- dem_clim |> 
  filter(
    k_type == "1_Natural" |
      k_type == "2_Natural"
    ) 

dem_clim_pred_obs <- append(
  dem_clim_new_pred, 
  c(list(dem_clim_obs_all),
  list(dem_clim_obs_p),
  list(dem_clim_obs_n))
  )
length(dem_clim_pred_obs)

names(dem_clim_pred_obs) <- c(
  "dem_clim_cc",
  "dem_clim_c2p_cc",
  "dem_clim_c2n_cc",
  "dem_clim_obs_all",
  "dem_clim_obs_p",
  "dem_clim_obs_n"
)

# add prediction name to each dataset
mutate_name <- function(x, names_df){
  dem_clim_pred_obs[[x]] |> 
    dplyr::mutate(
      df = names_df
    )
}

arg2_x_names_df <- list(
  x = 1:length(dem_clim_pred_obs), 
  names_df = names(dem_clim_pred_obs)
  )

dem_clim_pred_obs_n <- arg2_x_names_df |>
  pmap_df(mutate_name)

table(dem_clim_pred_obs_n$df)

dem_clim_all_pred_obs <- dem_clim_pred_obs_n |> 
  filter(df == "dem_clim_cc" |
           df == "dem_clim_obs_all")

table(dem_clim_all_pred_obs$k_type)
table(dem_clim_all_pred_obs$df)

dem_clim_all_pred_obs <- dem_clim_all_pred_obs |> 
  mutate(
    mortality_pred_obs = if_else(
      is.na(predFE), mort_real, predFE
    )
  )

summary(dem_clim_all_pred_obs$mort_real)
summary(dem_clim_all_pred_obs$predFE)

# https://cran.r-project.org/web/packages/ggdist/vignettes/slabinterval.html#multiple-slabs-and-intervals-in-composite-plots
# Quantile dotplots
gg_dem_clim_all_pred_obs <- dem_clim_all_pred_obs |>
  # when there is mortality (conditional part)
  filter(mort_real > 0) |> 
  mutate(
    k_type = recode_factor(
      k_type, 
      "1_Natural" = "C1 Natural",
      "1_Planted" = "C1 Planted",
      "2_Natural" = "C2 Natural",
      "2_Planted" = "C2 Planted"
    ),
    df = recode_factor(
      df, 
      "dem_clim_obs_all" = "Observed",
      "dem_clim_cc" = "Predicted"
    )
  ) |>
  ggplot(aes(x = k_type, y = mortality_pred_obs * 100,
             color = df, fill = df
             )) +
  stat_dots(
    scale = 0.5,
    quantiles = 50,
    .width = 0,
    alpha = .5,
    color = NA,
    size = 0
    ) +
    stat_halfeye(
    .width = 0,
    slab_fill = NA,
  ) +
  ylab(expression(paste("Mortality (%",~ha^-1~year^-1,")"))) +
  scale_fill_manual(values = c("#E1BE6A", "#40B0A6"),
                    guide = "none") +
  scale_color_manual(values = c("#E1BE6A", "#40B0A6")) +
  coord_cartesian(ylim = c(0, 3)) +
  theme(
    legend.position = "none",
    panel.grid.major = element_line(colour = "grey90", size = 0.5),
    panel.background = element_blank(),
    axis.text = element_text(size = 11, color = "black"),
    axis.title.y = element_text(size = 11),
    axis.title.x = element_blank()
  ) +
  guides(color = guide_legend(override.aes = list(linetype = 0))) +
  ggtitle("Observed data vs predictions increasing\nclimate change impacts")

gg_dem_clim_all_pred_obs

dem_clim_c_pred_obs <- dem_clim_pred_obs_n |> 
  filter(
    df == "dem_clim_c2p_cc" |
      df == "dem_clim_obs_p" |
      df == "dem_clim_c2n_cc" |
      df == "dem_clim_obs_n"
    )

table(dem_clim_c_pred_obs$k_type)
table(dem_clim_c_pred_obs$df)

dem_clim_c_pred_obs <- dem_clim_c_pred_obs |> 
  mutate(
    mortality_pred_obs = if_else(
      is.na(predFE), mort_real, predFE
    )
  )

gg_dem_clim_c_pred_obs <- dem_clim_c_pred_obs |>
  # when there is mortality (conditional part)
  filter(mort_real > 0) |>
  mutate(
    k_type = recode_factor(
      k_type, 
      "1_Natural" = "C2 Natural",
      "1_Planted" = "C2 Planted",
      "2_Natural" = "C2 Natural",
      "2_Planted" = "C2 Planted"
    ),
    df = recode_factor(
      df, 
      "dem_clim_obs_p" = "Observed",
      "dem_clim_c2p_cc" = "Predicted",
      "dem_clim_obs_n" = "Observed",
      "dem_clim_c2n_cc" = "Predicted",
    )
  ) |>
  ggplot(aes(x = k_type, y = mortality_pred_obs * 100,
             fill = df, color = df)) +
  stat_dots(
    scale = 0.5,
    quantiles = 50,
    .width = 0,
    alpha = .5,
    color = NA,
    size = .6
    ) +
    stat_halfeye(
    .width = 0,
    slab_fill = NA,
  ) +
  ylab(expression(paste("Mortality (%",~ha^-1~year^-1,")"))) +
  scale_fill_manual(values = c("#E1BE6A", "#40B0A6"),
                    guide = "none") +
  scale_color_manual(values = c("#E1BE6A", "#40B0A6")) +
  coord_cartesian(ylim = c(0, 3)) +
  theme(
    legend.key = element_blank(),
    legend.title = element_blank(),
    panel.grid.major = element_line(colour = "grey90", size = 0.5),
    panel.background = element_blank(),
    axis.text = element_text(size = 11, color = "black"),
    axis.title.y = element_text(size = 11),
    axis.title.x = element_blank()
  ) +
  guides(color = guide_legend(override.aes = list(linetype = 0))) +
  ggtitle("Observed data in natural & planted stands vs predictions\nsetting all natural stands as C2 Natural & setting all planted\nstands as C2 Planted & increasing climate change impacts")

gg_dem_clim_c_pred_obs

# save plots --------------------------------------------------------------
ggsave(
  plot = map_plot("WAIplot") + map_plot("speimin") +
    plot_annotation(tag_levels = "a"),
  here("03-results", "si_figures", "s3_wai_spei_distribution.png"),
  width = 12, height = 6
)

ggsave(
  plot = gg_dem_clim_all_pred_obs + 
    theme(legend.position = "none") +
    gg_dem_clim_c_pred_obs +
    plot_annotation(tag_levels = "a"),
  here("03-results", "main_figure", "main_plot.png"),
  width = 11, height = 5
)
```
